### ISSUE TITLE
wiki language switcher doesn't cope with the browser's back and forth function

### ISSUE THREAD

**Issue by Wolf-SO** [jakub-g/greasemonkey-userscripts#8]
When navigating with the browser's back and forth buttons, the first heading gets increasingly populated by language links. The effect is especially confusing because I rarely use these functions.

**Comment by Wolf-at-SO** [comment]
Sorry, I'm not an experienced user of GitHub, so I seem to have made duplicate changes or pull requests.

**Comment by Wolf-SO** [comment]
I cannot reproduce this issue anymore, so I close it.
